---
config:
    flowchart:
        defaultRenderer: elk
---

flowchart LR

subgraph 0["src"]
1["index.ts"]
subgraph 2["handlers"]
3["index.ts"]
4["config.ts"]
subgraph P["modules"]
Q["logs-socket.ts"]
1C["docker-socket.ts"]
1F["starter.ts"]
1K["live-stacks.ts"]
end
16["database.ts"]
17["docker.ts"]
1B["logs.ts"]
1J["sockets.ts"]
1L["stacks.ts"]
1U["utils.ts"]
end
subgraph B["core"]
subgraph C["database"]
D["index.ts"]
E["backup.ts"]
G["_dbState.ts"]
H["database.ts"]
M["helper.ts"]
S["config.ts"]
T["containerStats.ts"]
U["dockerHosts.ts"]
V["hostStats.ts"]
W["logs.ts"]
X["stacks.ts"]
end
subgraph N["utils"]
O["logger.ts"]
Y["helpers.ts"]
13["change-me-checker.ts"]
14["package-json.ts"]
1E["calculations.ts"]
end
subgraph Z["plugins"]
10["plugin-manager.ts"]
12["loader.ts"]
end
subgraph 19["docker"]
1A["client.ts"]
1G["scheduler.ts"]
1H["store-container-stats.ts"]
1I["store-host-stats.ts"]
end
subgraph 1M["stacks"]
1N["controller.ts"]
1P["checker.ts"]
subgraph 1Q["operations"]
1R["runStackCommand.ts"]
1S["stackHelpers.ts"]
1T["stackStatus.ts"]
end
end
end
end
subgraph 5["~"]
subgraph 6["typings"]
7["database"]
8["docker"]
9["plugin"]
F["misc"]
18["dockerode"]
1D["websocket"]
1O["docker-compose"]
end
end
subgraph A["fs"]
J["promises"]
end
I["bun:sqlite"]
K["os"]
L["path"]
R["stream"]
11["events"]
15["package.json"]
1-->3
3-->4
3-->16
3-->17
3-->1B
3-->1C
3-->1F
3-->1J
3-->1L
3-->1U
3-->1G
3-->10
3-->O
4-->D
4-->E
4-->10
4-->O
4-->14
4-->7
4-->8
4-->9
4-->A
D-->E
D-->S
D-->T
D-->H
D-->U
D-->V
D-->W
D-->X
E-->G
E-->H
E-->M
E-->O
E-->F
E-->A
H-->I
H-->A
H-->J
H-->K
H-->L
M-->G
M-->O
O-->G
O-->D
O-->Q
O-->7
O-->L
Q-->O
Q-->7
Q-->R
S-->H
S-->M
T-->H
T-->M
T-->7
U-->H
U-->M
U-->8
V-->H
V-->M
V-->8
W-->H
W-->M
W-->7
X-->Y
X-->H
X-->M
X-->7
Y-->O
10-->O
10-->12
10-->8
10-->9
10-->11
12-->13
12-->O
12-->10
12-->A
12-->L
13-->O
13-->J
14-->15
16-->D
17-->D
17-->1A
17-->O
17-->8
17-->18
1A-->O
1A-->8
1B-->D
1B-->O
1C-->Q
1C-->D
1C-->1A
1C-->1E
1C-->O
1C-->7
1C-->8
1C-->1D
1F-->1C
1F-->1G
1F-->10
1G-->D
1G-->1H
1G-->1I
1G-->O
1G-->7
1H-->O
1H-->D
1H-->1A
1H-->1E
1H-->7
1I-->D
1I-->1A
1I-->O
1I-->8
1I-->18
1J-->1C
1J-->1K
1J-->Q
1K-->O
1K-->R
1L-->D
1L-->1N
1L-->O
1L-->7
1N-->1C
1N-->1P
1N-->1R
1N-->1S
1N-->1T
1N-->D
1N-->O
1N-->7
1N-->1O
1N-->J
1P-->D
1P-->O
1R-->1C
1R-->1S
1R-->O
1R-->1O
1S-->D
1S-->Y
1S-->O
1S-->1O
1T-->1R
1T-->D
1T-->O
1U-->O

