---
config:
    flowchart:
        defaultRenderer: elk
---

flowchart LR

subgraph 0["src"]
1["index.ts"]
subgraph 2["core"]
subgraph 3["docker"]
4["monitor.ts"]
V["client.ts"]
19["scheduler.ts"]
1A["store-host-stats.ts"]
1C["store-container-stats.ts"]
end
subgraph 6["plugins"]
7["plugin-manager.ts"]
1E["loader.ts"]
end
subgraph 9["utils"]
A["logger.ts"]
W["swagger-readme.ts"]
15["response-handler.ts"]
17["package-json.ts"]
1D["calculations.ts"]
1F["change-me-checker.ts"]
end
subgraph C["database"]
D["index.ts"]
E["config.ts"]
F["database.ts"]
H["helper.ts"]
I["containerStats.ts"]
J["dockerHosts.ts"]
M["hostStats.ts"]
N["logs.ts"]
P["stacks.ts"]
end
subgraph 11["stacks"]
12["controller.ts"]
end
subgraph 1G["trpc"]
1H["index.ts"]
1I["router.ts"]
subgraph 1J["procedures"]
1K["api-config.procedure.ts"]
1M["docker-manager.procedure.ts"]
1N["docker-stats.procedure.ts"]
1O["logs.procedure.ts"]
1P["stacks.procedure.ts"]
end
1L["trpc.ts"]
end
end
subgraph K["typings"]
L["docker.ts"]
O["websocket.ts"]
Q["database.ts"]
R["docker-compose.ts"]
U["plugin.ts"]
Z["elysiajs.ts"]
1B["dockerode.ts"]
end
subgraph S["routes"]
T["live-logs.ts"]
10["stacks.ts"]
16["utils.ts"]
1Q["api-config.ts"]
1R["docker-manager.ts"]
1S["docker-stats.ts"]
1T["docker-websocket.ts"]
1V["logs.ts"]
end
subgraph X["middleware"]
Y["auth.ts"]
end
end
5["bun"]
8["events"]
B["path"]
G["bun:sqlite"]
subgraph 13["fs"]
14["promises"]
end
18["package.json"]
1U["stream"]
1-->4
1-->W
1-->Y
1-->T
1-->10
1-->16
1-->Q
1-->D
1-->19
1-->1E
1-->1H
1-->A
1-->1Q
1-->1R
1-->1S
1-->1T
1-->1V
4-->7
4-->D
4-->V
4-->A
4-->L
4-->L
4-->5
7-->A
7-->L
7-->U
7-->8
A-->D
A-->T
A-->O
A-->B
D-->E
D-->I
D-->F
D-->J
D-->M
D-->N
D-->P
E-->F
E-->H
F-->G
H-->A
I-->F
I-->H
J-->F
J-->H
J-->L
M-->F
M-->H
M-->L
N-->F
N-->H
N-->O
P-->F
P-->H
P-->Q
P-->R
T-->A
T-->O
U-->L
V-->A
V-->L
Y-->D
Y-->A
Y-->Q
Y-->Z
10-->D
10-->12
10-->A
10-->15
12-->D
12-->A
12-->Q
12-->R
12-->5
12-->14
15-->A
15-->Z
16-->17
16-->15
17-->18
19-->D
19-->1A
19-->1C
19-->A
19-->Q
1A-->D
1A-->V
1A-->A
1A-->L
1A-->1B
1C-->A
1C-->D
1C-->V
1C-->1D
1E-->1F
1E-->A
1E-->7
1E-->13
1E-->B
1F-->A
1F-->14
1H-->1I
1I-->1K
1I-->1M
1I-->1N
1I-->1O
1I-->1P
1I-->1L
1K-->1L
1K-->D
1K-->A
1K-->17
1K-->Q
1M-->1L
1M-->D
1M-->A
1M-->L
1N-->1L
1N-->D
1N-->V
1N-->1D
1N-->A
1N-->L
1N-->1B
1O-->1L
1O-->D
1O-->A
1P-->1L
1P-->D
1P-->12
1P-->A
1Q-->D
1Q-->7
1Q-->A
1Q-->17
1Q-->15
1Q-->Y
1Q-->Q
1R-->D
1R-->A
1R-->15
1R-->L
1S-->D
1S-->V
1S-->1D
1S-->A
1S-->15
1S-->L
1S-->1B
1T-->D
1T-->V
1T-->1D
1T-->A
1T-->15
1T-->1U
1V-->D
1V-->A

