---
config:
    flowchart:
        defaultRenderer: elk
---

flowchart LR

subgraph 0["src"]
1["index.ts"]
subgraph 2["core"]
subgraph 3["docker"]
4["monitor.ts"]
K["client.ts"]
U["scheduler.ts"]
V["store-host-stats.ts"]
X["store-container-stats.ts"]
end
subgraph 6["plugins"]
7["plugin-manager.ts"]
Z["loader.ts"]
end
subgraph 9["utils"]
A["logger.ts"]
T["respone-handler.ts"]
Y["calculations.ts"]
11["change-me-checker.ts"]
19["package-json.ts"]
end
subgraph C["database"]
D["repository.ts"]
F["helper.ts"]
end
subgraph Q["stacks"]
R["controller.ts"]
end
subgraph 13["trpc"]
14["index.ts"]
15["router.ts"]
subgraph 16["procedures"]
17["api-config.procedure.ts"]
1B["docker-manager.procedure.ts"]
1C["docker-stats.procedure.ts"]
1D["logs.procedure.ts"]
1E["stacks.procedure.ts"]
end
18["trpc.ts"]
end
end
subgraph G["typings"]
H["database.ts"]
I["docker.ts"]
J["plugin.ts"]
N["elysiajs.ts"]
S["docker-compose.ts"]
W["dockerode.ts"]
1K["websocket.ts"]
end
subgraph L["middleware"]
M["auth.ts"]
end
subgraph O["routes"]
P["stacks.ts"]
1F["api-config.ts"]
1G["docker-manager.ts"]
1H["docker-stats.ts"]
1I["docker-websocket.ts"]
1L["logs.ts"]
end
end
5["bun"]
8["events"]
B["path"]
E["bun:sqlite"]
subgraph 10["fs"]
12["promises"]
end
1A["package.json"]
1J["stream"]
1-->4
1-->M
1-->P
1-->H
1-->D
1-->U
1-->Z
1-->14
1-->A
1-->1F
1-->1G
1-->1H
1-->1I
1-->1L
4-->7
4-->D
4-->K
4-->A
4-->I
4-->I
4-->5
7-->A
7-->I
7-->J
7-->5
7-->8
A-->D
A-->B
D-->F
D-->A
D-->H
D-->I
D-->E
F-->A
J-->I
K-->A
K-->I
M-->D
M-->A
M-->H
M-->N
P-->D
P-->R
P-->A
P-->T
R-->D
R-->A
R-->H
R-->S
T-->A
T-->N
U-->D
U-->V
U-->X
U-->A
U-->H
V-->D
V-->K
V-->A
V-->I
V-->W
X-->D
X-->K
X-->Y
Z-->11
Z-->A
Z-->7
Z-->10
Z-->B
11-->A
11-->12
14-->15
15-->17
15-->1B
15-->1C
15-->1D
15-->1E
15-->18
17-->18
17-->D
17-->A
17-->19
17-->H
19-->1A
1B-->18
1B-->D
1B-->A
1C-->18
1C-->D
1C-->K
1C-->Y
1C-->A
1C-->I
1C-->W
1D-->18
1D-->D
1D-->A
1E-->18
1E-->D
1E-->R
1E-->A
1F-->D
1F-->A
1F-->19
1F-->T
1F-->M
1F-->H
1G-->D
1G-->A
1G-->T
1H-->D
1H-->K
1H-->Y
1H-->A
1H-->T
1H-->I
1H-->W
1I-->D
1I-->K
1I-->Y
1I-->A
1I-->T
1I-->I
1I-->1K
1I-->1J
1K-->1J
1L-->D
1L-->A

