networks:
  shared-network:
    driver: bridge

services:
  master:
    container_name: master
    environment:
      - NODE_ENV=development
      - HA_MASTER=true
      - HA_MASTER_IP=master:9876
      - HA_NODE=slave:9876
      - HA_UNSAFE=true
    volumes:
      - ./docker/master:/api/src/data
    ports:
      - 9876:9876
    image: dockstatapi:local
    networks:
      - shared-network
    depends_on:
      - slave
      - test-socket-proxy
  slave:
    container_name: slave
    environment:
      - NODE_ENV=development
    volumes:
      - ./docker/slave:/api/src/data
    ports:
      - 6789:9876
    image: dockstatapi:local
    networks:
      - shared-network

  test-socket-proxy:
    image: lscr.io/linuxserver/socket-proxy:latest
    container_name: test-socket-proxy
    environment:
      - ALLOW_START=1 #optional
      - ALLOW_STOP=1 #optional
      - ALLOW_RESTARTS=1 #optional
      - AUTH=0 #optional
      - BUILD=0 #optional
      - COMMIT=0 #optional
      - CONFIGS=0 #optional
      - CONTAINERS=1 #optional
      - DISABLE_IPV6=0 #optional
      - DISTRIBUTION=0 #optional
      - EVENTS=1 #optional
      - EXEC=0 #optional
      - IMAGES=0 #optional
      - INFO=1 #optional
      - NETWORKS=1 #optional
      - NODES=1 #optional
      - PING=1 #optional
      - POST=0 #optional
      - PLUGINS=0 #optional
      - SECRETS=0 #optional
      - SERVICES=0 #optional
      - SESSION=0 #optional
      - SWARM=0 #optional
      - SYSTEM=0 #optional
      - TASKS=0 #optional
      - VERSION=1 #optional
      - VOLUMES=0 #optional
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: unless-stopped
    read_only: true
    tmpfs:
      - /run
    networks:
      - shared-network
