log:
  logsize: 10 # Specify the Size of the log files in MB, default is 1MB
  LogCount: 1 # How many log files should be kept in rotation. Default is 5

hosts:
  YourHost1:
    url: 1.1.1.1
    port: 2375

  YourHost2:
    url: 2.2.2.2
    port: 2375

  YourHost3:
    url: 3.3.3.3
    port: 2375

mintimeout: 10000 # The minimum time to wait before querying the same server again, defaults to 5000 Ms
