# Stage 1: Build stage
FROM node:20-alpine AS builder

LABEL maintainer="https://github.com/its4nik"
LABEL version="2.0.1"
LABEL description="API for DockStat"
LABEL license="BSD-3-Clause license"
LABEL repository="https://github.com/its4nik/dockstatapi"
LABEL documentation="https://github.com/its4nik/dockstatapi"
LABEL org.opencontainers.image.description="The DockSatAPI is a free and OpenSource backend for gathering container statistics across hosts"
LABEL org.opencontainers.image.licenses="BSD-3-Clause license"
LABEL org.opencontainers.image.source="https://github.com/its4nik/dockstatapi"

WORKDIR /app

ENV NODE_NO_WARNINGS=1

RUN apk add --no-cache curl bash

COPY package*.json tsconfig.json environment.d.ts ./

RUN npm ci --include=dev

COPY ./src ./src
RUN mv ./src/sample-variable.json ./src/data/variables.json

RUN npm run build

# --------------------------------------
# Stage 2: Dependency pruning stage
FROM node:20-alpine AS deps
WORKDIR /api
COPY --from=builder /app/package*.json .
RUN npm ci --omit=dev

# --------------------------------------
# Stage 3: Final production image
FROM node:20-alpine AS prod

WORKDIR /api

RUN apk add --no-cache docker-cli bash curl && \
    mkdir -p /usr/libexec/docker/cli-plugins && \
    curl -sSL "https://github.com/docker/compose/releases/latest/download/docker-compose-linux-$(uname -m)" \
    -o /usr/libexec/docker/cli-plugins/docker-compose && \
    chmod +x /usr/libexec/docker/cli-plugins/docker-compose && \
    rm -rf /var/cache/apk/*

ARG USER_ID=10001
ARG GROUP_ID=10001
RUN addgroup -g $GROUP_ID dockstatapi && \
    adduser -u $USER_ID -G dockstatapi -h /api -s /bin/sh -D dockstatapi

COPY --from=builder --chown=dockstatapi:dockstatapi /app/dist/src ./src
COPY --from=builder --chown=dockstatapi:dockstatapi /app/src/config/swagger.yaml ./src/config/swagger.yaml
COPY --from=builder --chown=dockstatapi:dockstatapi /app/src/utils/assets ./src/utils/assets
COPY --from=deps --chown=dockstatapi:dockstatapi /api/node_modules ./node_modules

COPY --from=builder --chown=dockstatapi:dockstatapi /app/src/misc/entrypoint.sh .
COPY --from=builder --chown=dockstatapi:dockstatapi /app/src/misc/createEnvFile.sh .
RUN chmod +x *.sh

RUN mkdir -p /api/src/data && \
    chown -R dockstatapi:dockstatapi /api && \
    chmod -R 755 /api && \
    chmod 775 /api/src/data

HEALTHCHECK --interval=5m --timeout=3s \
    CMD curl -f http://localhost:9876/api/status || exit 1

EXPOSE 9876
STOPSIGNAL 130
USER dockstatapi

ENTRYPOINT [ "sh", "./entrypoint.sh", "--dev" ]
