import vars from "../data/variables.json";

export const {
  VERSION,
  RUNNING_IN_DOCKER,
  TRUSTED_PROXYS,
  HA_MASTER,
  HA_MASTER_IP,
  HA_NODE,
  HA_UNSAFE,
  DISCORD_WEBHOOK_URL,
  EMAIL_SENDER,
  EMAIL_RECIPIENT,
  EMAIL_PASSWORD,
  EMAIL_SERVICE,
  PUSHBULLET_ACCESS_TOKEN,
  PUSHOVER_USER_KEY,
  PUSHOVER_API_TOKEN,
  SLACK_WEBHOOK_URL,
  TELEGRAM_BOT_TOKEN,
  TELEGRAM_CHAT_ID,
  WHATSAPP_API_URL,
  WHATSAPP_RECIPIENT,
} = vars;
