name: Anchore Grype vulnerability scan

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main", "dev"]
  schedule:
    - cron: "30 9 * * 1"

permissions:
  contents: read

jobs:
  Anchore-Build-Scan:
    permissions:
      contents: read
      security-events: write # for github/codeql-action/upload-sarif to upload SARIF results
      actions: read # only required for a private repository by github/codeql-action/upload-sarif to get the Action run status
    runs-on: ubuntu-latest
    steps:
      - name: Check out the code
        uses: actions/checkout@4
      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag localbuild/testimage:latest
      - name: Run the Anchore Grype scan action
        uses: anchore/scan-action@d5aa5b6cb9414b0c7771438046ff5bcfa2854ed7
        id: scan
        with:
          image: "localbuild/testimage:latest"
          fail-build: true
          severity-cutoff: critical
      - name: Upload vulnerability report
        uses: github/codeql-action/upload-sarif
        with:
          sarif_file: ${{ steps.scan.outputs.sarif }}
