name: "Build and Push Docker Image"

on:
  release:
    types: [published]

permissions:
  packages: write
  contents: read

jobs:
  build-release:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Extract version and create tag
        id: get-tag
        run: |
          # Remove 'v' prefix from release tag if present
          VERSION="${GITHUB_REF#refs/tags/v}"
          # Check if pre-release and append '-pre'
          if ${{ github.event.release.prerelease }}; then
            TAG="$VERSION-pre"
          else
            TAG="$VERSION"
          fi
          echo "tag=$TAG" >> $GITHUB_OUTPUT

      - name: Generate Docker metadata
        uses: docker/metadata-action@v5
        id: metadata
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=${{ steps.get-tag.outputs.tag }}
            type=raw,value=latest,enable=${{ !github.event.release.prerelease }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          platforms: linux/amd64,linux/arm64
          context: .
          file: docker/Dockerfile-base
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
