name: Count Lines of Code

permissions:
  issues: write
  pull-requests: write

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, dev ]

jobs:
  cloc:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Count Lines of Code (cloc)
      uses: djdefi/cloc-action@6
      with:
        options: --md --report-file=cloc.md --exclude-dir=node_modules
    
    - name: Create comment from markdown file
      uses: GrantBirki/comment@v2.1.0
      with:
        file: cloc.md