name: Generate Dependency Graph

on:
  push:

permissions: write-all

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependency-cruiser and graphviz
        run: |
          bun add dependency-cruiser
          sudo apt-get install -y graphviz

      - name: Generate SVG Dependency Graph
        run: |
          bun run dependency-cruiser --output-type ddot src/index.ts --no-config -x node_modules --ts-pre-compilation-deps --ts-config tsconfig.json | dot -T svg > dependency-graph.svg
          echo "SVG graph generated at docs/dependency-graph.svg"

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "dependency-graph*"
          message: "Update dependency graphs"
          committer_name: "GitHub Action"
          committer_email: "action@github.com"
