name: Generate Dependency Graph

on:
  push:

permissions: write-all

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: oven-sh/setup-bun@v2

      - name: Install dependency-cruiser and graphviz
        run: |
          bun add dependency-cruiser
          sudo apt-get install -y graphviz

      - name: Generate Mermaid Dependency Graph
        run: |
          bun run dependency-cruiser --output-type mermaid src/index.ts --output-to dependency-graph.mmd --no-config -x node_modules --ts-pre-compilation-deps --ts-config tsconfig.json
          echo "Mermaid graph generated at dependency-graph.mmd"

      - name: Convert to ELK Layout
        run: |
          bash ./.github/scripts/dep-graph.sh

      - name: Generate Dependency Graph (SVG)
        run: |
          bun run dependency-cruiser --output-type dot src/index.ts --output-to dependency-graph.dot --no-config -x node_modules --ts-pre-compilation-deps --ts-config tsconfig.json
          dot -T svg -Gsplines=ortho dependency-graph.dot -o dependency-graph.svg
          echo "SVG graph generated at dependency-graph.svg"

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          add: "dependency-graph*"
          message: "Update dependency graphs"
          committer_name: "GitHub Action"
          committer_email: "action@github.com"
