name: Licensed

on: [push]

jobs:
  license-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest code
        uses: actions/checkout@4
      - name: Use Node.js 20.x
        uses: actions/setup-node
        with:
          node-version: 20.x
      - name: Run npm install
        run: npm install
      - name: Check licenses
        uses: tangro/actions-license-check
        with:
          allowed-licenses: "MIT; ISC; Apache-2.0; Custom: https://www.telerik.com/kendo-angular-ui/; Custom: https://www.telerik.com/kendo-react-ui/; BSD"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_CONTEXT: ${{ toJson(github) }}
