name: Docker Build and Test Workflow

on:
  push:
    branches: ["**"]
  release:
    types: [published, prereleased]

permissions:
  contents: write
  checks: write
  id-token: write
  pull-requests: write
  packages: write
  security-events: write

jobs:
  test:
    name: Test Build on Push
    runs-on: ubuntu-latest
    steps:
      - uses: oven-sh/setup-bun@v2
        name: Setup Bun
        with:
          bun-version: latest

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint
        run: |
          bun install
          bun clean
          bun biome ci
          bun knip --reporter markdown > .github/Knip-Report.md

      - name: Commit and Push Changes
        uses: EndBug/add-and-commit@v9
        with:
          commit: "-f"
          add: '["src/",".github/Knip-Report.md"]'
          message: "Update dependency graphs and upload Knip-report.md"
          committer_name: "GitHub Action"
          committer_email: "action@github.com"

      - name: Start proxy
        run: |
          docker compose -f docker/docker-compose.dev.yaml up -d

      - name: Run Unit-tests
        run: |
          bun test --reporter=junit --reporter-outfile=./unit-test.xml
          ls -lah

      - name: Publish Test Report
        uses: mikepenz/action-junit-report@v5
        with:
          include_passed: true
          report_paths: |
            unit-test.xml

      - name: Run Docker Build
        run: |
          bun build:docker

      - name: Start Docker container and check uptime
        run: |
          docker run --name dockstatapi --rm -d dockstatapi:local
          sleep 30
          if docker ps --filter "name=dockstatapi" --filter "status=running" | grep dockstatapi; then
            docker kill dockstatapi
            exit 0
          else
            exit 1
          fi

  release:
    name: Build and Push Docker Image on Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Determine image tag
        id: tag
        run: |
          TAG=${GITHUB_REF##*/}
          if [ "${{ github.event.release.prerelease }}" = "true" ]; then
            TAG="${TAG}-rc"
          fi
          echo "IMAGE_TAG=$TAG" >> $GITHUB_ENV
          echo "Using tag: $TAG"

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: docker/Dockerfile
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ghcr.io/its4nik/dockstatapi:${{ env.IMAGE_TAG }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: 'ghcr.io/its4nik/dockstatapi:${{ env.IMAGE_TAG }}'
          format: 'sarif'
          output: 'trivy-results-${{ env.IMAGE_TAG }}.sarif'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: "MEDIUM,HIGH,CRITICAL"

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-${{ env.IMAGE_TAG }}.sarif'

      - name: Scan image dependencies
        uses: aquasecurity/trivy-action@0.28.0
        with:
          image-ref: "ghcr.io/its4nik/dockstatapi:${{ env.IMAGE_TAG }}"
          scan-type: image
          format: 'github'
          output: 'dependency-results.sbom.json'
          github-pat: ${{ secrets.GITHUB_TOKEN }} 
          severity: "MEDIUM,HIGH,CRITICAL"
          scanners: "vuln"

      - name: Upload trivy report as a Github artifact
        uses: actions/upload-artifact@v4
        with:
          name: trivy-sbom-report
          path: '${{ github.workspace }}/dependency-results.sbom.json'
          retention-days: 20
